version: "3.8"
services:

  workshop:
    container_name: 'WorkShopService'
    build:
      context: ./API_ts
    command: npm start
    ports:
      - "8002:8002"
    volumes:
      - .API_ts:/usr/src/app/workshop
      - /usr/src/app/workshop/node_modules

  krakend_gateway:
    container_name: 'APIGateway'
    image: devopsfaith/krakend:1.2.0
    volumes:
      - ./KrakenD:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - workshop
    restart: always
